#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 60000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "3WNoB/eaW30R"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

